---
title: "Exercise: Rule Metrics, the Apriori Algorithm, and FP-Growth"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load-packages}
library(tidyverse)
library(arules)
```

## Task 1: Compute all five rule metrics from a 10,000-policyholder table

Use the counts from the Concept section.

```{r task1-data}
N <- 10000
count_D  <- 6600   # policyholders with Dental
count_V  <- 5700   # policyholders with Vision
count_DV <- 2800   # policyholders with both Dental AND Vision
```

```{r task1-support}
# TODO: compute support of {Dental}, {Vision}, and the rule {Dental} => {Vision}
supp_D  <- NULL   # count_D  / N
supp_V  <- NULL   # count_V  / N
supp_DV <- NULL   # count_DV / N

cat("supp({Dental})        =", supp_D, "\n")
cat("supp({Vision})        =", supp_V, "\n")
cat("supp({D, V})          =", supp_DV, "\n")
```

```{r task1-confidence-lift}
# TODO: confidence and lift for Dental => Vision
conf_DV <- NULL   # supp_DV / supp_D
lift_DV <- NULL   # conf_DV / supp_V

cat("conf(D => V) =", conf_DV, "\n")
cat("lift(D => V) =", lift_DV, "\n")
# Is Dental positively or negatively associated with Vision? Comment:
```

```{r task1-conviction-leverage}
# TODO: conviction and leverage for Dental => Vision
conv_DV <- NULL   # (1 - supp_V) / (1 - conf_DV)
lev_DV  <- NULL   # supp_DV - supp_D * supp_V

cat("conv(D => V) =", conv_DV, "\n")
cat("lev (D => V) =", lev_DV, "\n")
```

## Task 2: Trace Apriori on the 5-transaction database

```{r task2-data}
trans_list <- list(
  T1 = c("Dental", "Vision"),
  T2 = c("Dental", "Mental", "Vision"),
  T3 = c("Vision", "Maternity"),
  T4 = c("Dental", "Mental"),
  T5 = c("Dental", "Vision", "Mental")
)
N5 <- length(trans_list)
min_supp <- 0.60

contains <- function(tl, items) {
  sum(sapply(tl, function(t) all(items %in% t)))
}
```

```{r task2-pass1}
# TODO: compute support for each 1-item and decide if it is frequent
items_1 <- c("Dental", "Vision", "Mental", "Maternity")
for (item in items_1) {
  s <- contains(trans_list, item) / N5
  cat(item, ": supp =", s, "| frequent:", s >= min_supp, "\n")
}
# Which items form L1?
```

```{r task2-pass2}
# TODO: compute support for the three candidate 2-itemsets from L1
# {Dental, Vision}, {Dental, Mental}, {Vision, Mental}
for (pair in list(c("Dental","Vision"), c("Dental","Mental"), c("Vision","Mental"))) {
  s <- contains(trans_list, pair) / N5
  cat("{", paste(pair, collapse=", "), "}: supp =", s, "| frequent:", s >= min_supp, "\n")
}
# Which itemsets form L2?
# Is {Dental, Vision, Mental} pruned before Pass 3? Why?
```

## Task 3: Run apriori() and eclat()

```{r task3-convert}
trans <- as(trans_list, "transactions")
inspect(trans)
```

```{r task3-apriori}
# TODO: run apriori() with supp = 0.40, conf = 0.60, minlen = 2
rules_ap <- NULL   # apriori(trans, parameter = list(...))
# inspect(sort(rules_ap, by = "lift"))
```

```{r task3-eclat}
# TODO: run eclat() then ruleInduction() with the same thresholds
freq_sets   <- NULL   # eclat(trans, parameter = list(supp = 0.40, minlen = 2))
rules_eclat <- NULL   # ruleInduction(freq_sets, trans, confidence = 0.60)
# inspect(sort(rules_eclat, by = "lift"))
```

## Task 4: Compare Apriori and ECLAT results

```{r task4-compare}
# TODO: inspect the top 5 rules by lift from both algorithms
# Are they identical? If not, why might they differ?

# Comment on which algorithm you would prefer for n = 500,000 and why:
```
